"""Add portfolio management tables

Revision ID: 368cadbd105f
Revises: e1b349111630
Create Date: 2025-09-27 21:24:50.472206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368cadbd105f'
down_revision: Union[str, None] = 'e1b349111630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_performances_date'), 'daily_performances', ['date'], unique=True)
    op.create_index(op.f('ix_daily_performances_id'), 'daily_performances', ['id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('shares', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('buy_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_portfolios_ticker'), 'portfolios', ['ticker'], unique=False)
    op.create_table('trade_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('shares', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_logs_date'), 'trade_logs', ['date'], unique=False)
    op.create_index(op.f('ix_trade_logs_id'), 'trade_logs', ['id'], unique=False)
    op.create_index(op.f('ix_trade_logs_ticker'), 'trade_logs', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_logs_ticker'), table_name='trade_logs')
    op.drop_index(op.f('ix_trade_logs_id'), table_name='trade_logs')
    op.drop_index(op.f('ix_trade_logs_date'), table_name='trade_logs')
    op.drop_table('trade_logs')
    op.drop_index(op.f('ix_portfolios_ticker'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_daily_performances_id'), table_name='daily_performances')
    op.drop_index(op.f('ix_daily_performances_date'), table_name='daily_performances')
    op.drop_table('daily_performances')
    # ### end Alembic commands ###
